# NOTE: update this with your service name
service: babysitter-management-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
